### ISSUE TITLE
Create Labelmap and TFRecords/ValueError: 'nickel' is not in list

### ISSUE THREAD

**Issue by Krump12** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#162]
Traceback (most recent call last):
  File "/content/create_tfrecord.py", line 128, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/content/create_tfrecord.py", line 106, in main
    tf_example = create_tf_example(group, path)
  File "/content/create_tfrecord.py", line 73, in create_tf_example
    classes.append(int(labels.index(row['class'])+1))
ValueError: 'nickel' is not in list
how to solve...

**Comment by Krump12** [comment]
![image](https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi/assets/105976851/074fd40b-3563-4b54-8303-2cd2b1084080)
