### ISSUE TITLE
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by SaranRavella123** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#173]
Hello. I'm very new to this and I watched your video on how to use raspberrypi to do object detection. Everything went smoothly, except in the end I'm having trouble because I don't know how to resolve this error.

(tflite1-env) saran@welcomegateiot:~/tflite1 $ python3 TFLite_detection_webcam.py --modeldir=Sample_TFLite_model
Traceback (most recent call last):
  File "/home/saran/tflite1/tflite1-env/lib/python3.9/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/saran/tflite1/tflite1-env/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/saran/tflite1/tflite1-env/lib/python3.9/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/saran/tflite1/tflite1-env/lib/python3.9/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/home/saran/tflite1/tflite1-env/lib/python3.9/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/home/saran/tflite1/tflite1-env/lib/python3.9/site-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/home/saran/tflite1/tflite1-env/bin/python3"
  * The NumPy version is: "1.26.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libopenblas.so.0: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/saran/tflite1/tflite1-env/lib/python3.9/site-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
Traceback (most recent call last):
  File "/home/saran/tflite1/TFLite_detection_webcam.py", line 19, in <module>
    import cv2
  File "/home/saran/tflite1/tflite1-env/lib/python3.9/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import

**Comment by theprotector** [comment]
I was getting the same error (up to date Bullseye on a Pi4). Try

sudo apt install libopenblas-base libopenblas-dev

which resolved the python error for me.
