### ISSUE TITLE
Error running TFLite_detection_webcam.py -- RPI4 (BUSTER)

### ISSUE THREAD

**Issue by IsaacMG91** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#23]
Hello,

The next error appears when running the file TFLite_detection_webcam.py 

 File "TFLite_detection_video.py", line 115, in <module>
    if labels[0] == '???':
IndexError: list index out of range

I commented this lines and then a new error appeared:

Traceback (most recent call last):
  File "TFLite_detection_webcam.py", line 119, in <module>
    interpreter = Interpreter(model_path=PATH_TO_CKPT)
  File "/home/pi/tflite1/tflite1-env/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter.py", line 206, in __init__
    model_path))
ValueError: Mmap of '/home/pi/tflite1/Sample_TFLite_model/detect.tflite' failed.

Anybody that could help? Could be due to the tensorflow version? I just followed the tutorial step by step.

**Comment by IsaacMG91** [comment]
Solved:  for some reason the files after decompressing the model were empty.
