### ISSUE TITLE
ValueError: ('%s is not decorated with @add_arg_scope', ('nets.mobilenet.mobilenet', 'depth_multiplier'))

### ISSUE THREAD

**Issue by adriacabeza** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#67]
Hi, I get a weird error when I am about to start fine tuning the ssd mobilenet v2 checkpoint: 
```bash 
python models/research/object_detection/legacy/train.py --alsologtostderr --train_dir=train  --pipeline_config_path=ssd_mobilenet_v2_quantized_300x300_coco.config
```

Error: 
```bash
Traceback (most recent call last):
  File "models/research/object_detection/legacy/train.py", line 186, in <module>
    tf.app.run()
  File "/workspace/workspace/test/.env/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/workspace/workspace/test/.env/lib/python3.5/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/workspace/workspace/test/.env/lib/python3.5/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/workspace/workspace/test/.env/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "models/research/object_detection/legacy/train.py", line 182, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/workspace/workspace/test/.env/lib/python3.5/site-packages/object_detection/legacy/trainer.py", line 291, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "/workspace/workspace/test/models/research/slim/deployment/model_deploy.py", line 192, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/workspace/workspace/test/.env/lib/python3.5/site-packages/object_detection/legacy/trainer.py", line 204, in _create_losses
    prediction_dict = detection_model.predict(images, true_image_shapes)
  File "/workspace/workspace/test/.env/lib/python3.5/site-packages/object_detection/meta_architectures/ssd_meta_arch.py", line 568, in predict
    preprocessed_inputs)
  File "/workspace/workspace/test/.env/lib/python3.5/site-packages/object_detection/models/ssd_mobilenet_v2_feature_extractor.py", line 118, in extract_features
    [mobilenet.depth_multiplier], min_depth=self._min_depth):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/workspace/workspace/test/.env/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 152, in arg_scope
    _name_op(op))
ValueError: ('%s is not decorated with @add_arg_scope', ('nets.mobilenet.mobilenet', 'depth_multiplier'))
```

I am using the last version of the models repository and I've only changed the directory paths for the records, labelmaps, the number of classes and number of testing samples.  Moreover I am using the 1.14.0 of Tensorflow.

How can I solve it?

**Comment by Petros626** [comment]
> Hi, I get a weird error when I am about to start fine tuning the ssd mobilenet v2 checkpoint:
> 
> ```shell
> python models/research/object_detection/legacy/train.py --alsologtostderr --train_dir=train  --pipeline_config_path=ssd_mobilenet_v2_quantized_300x300_coco.config
> ```
> 
> Error:
> 
> ```shell
> Traceback (most recent call last):
>   File "models/research/object_detection/legacy/train.py", line 186, in <module>
>     tf.app.run()
>   File "/workspace/workspace/test/.env/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 40, in run
>     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
>   File "/workspace/workspace/test/.env/lib/python3.5/site-packages/absl/app.py", line 299, in run
>     _run_main(main, args)
>   File "/workspace/workspace/test/.env/lib/python3.5/site-packages/absl/app.py", line 250, in _run_main
>     sys.exit(main(argv))
>   File "/workspace/workspace/test/.env/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
>     return func(*args, **kwargs)
>   File "models/research/object_detection/legacy/train.py", line 182, in main
>     graph_hook_fn=graph_rewriter_fn)
>   File "/workspace/workspace/test/.env/lib/python3.5/site-packages/object_detection/legacy/trainer.py", line 291, in train
>     clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
>   File "/workspace/workspace/test/models/research/slim/deployment/model_deploy.py", line 192, in create_clones
>     outputs = model_fn(*args, **kwargs)
>   File "/workspace/workspace/test/.env/lib/python3.5/site-packages/object_detection/legacy/trainer.py", line 204, in _create_losses
>     prediction_dict = detection_model.predict(images, true_image_shapes)
>   File "/workspace/workspace/test/.env/lib/python3.5/site-packages/object_detection/meta_architectures/ssd_meta_arch.py", line 568, in predict
>     preprocessed_inputs)
>   File "/workspace/workspace/test/.env/lib/python3.5/site-packages/object_detection/models/ssd_mobilenet_v2_feature_extractor.py", line 118, in extract_features
>     [mobilenet.depth_multiplier], min_depth=self._min_depth):
>   File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
>     return next(self.gen)
>   File "/workspace/workspace/test/.env/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 152, in arg_scope
>     _name_op(op))
> ValueError: ('%s is not decorated with @add_arg_scope', ('nets.mobilenet.mobilenet', 'depth_multiplier'))
> ```
> 
> I am using the last version of the models repository and I've only changed the directory paths for the records, labelmaps, the number of classes and number of testing samples. Moreover I am using the 1.14.0 of Tensorflow.
> 
> How can I solve it?

You need to install tf-slim 1.1.0
